# name: GitHub Actions Vercel Preview Deployment
# on:
#   push:
#     branches-ignore:
#       - main
# concurrency:
#   group: ${{ github.ref }}-vercel-preview
#   cancel-in-progress: true

# jobs:
#   Deploy-Preview:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: read
#     env:
#       COMMIT_SHA: ${{ github.sha }}
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: recursive
#           fetch-depth: 0

#       - uses: DeterminateSystems/nix-installer-action@main
#         with:
#           determinate: true
#       - uses: DeterminateSystems/flakehub-cache-action@main

#       - run: npm install -g pnpm@latest-10
#       - run: ./prep-sushi.sh

#       - name: Install Vercel CLI
#         run: npm install --global vercel@canary
#       - name: Pull Vercel Environment Information
#         run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

#       - name: Nix Shell
#         run: nix develop
#       - name: Vercel Build
#         run: vercel build
#       - name: Deploy Project Artifacts to Vercel
#         run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
